### ISSUE TITLE
Execute script for all drivers does not work when passed an extremely large results

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-nuget#80]
The `execute` command for each driver has a maximum allowed character / size length before the driver errors. We need to change how we are injecting the partial for `finishRun` in order to support extremely large results.

See https://github.com/dequelabs/axe-core-npm/pull/667

**Comment by padmavemulapati** [comment]
To test this, as per the doucment, used the below code
```
AxeBuilderOptions axeBuilderOptions = new AxeBuilderOptions
{
    ScriptProvider = new FileAxeScriptProvider(".\\axe-large-partial.js")
};
AxeResult axeResult = new AxeBuilder(webDriver, axeBuilderOptions).Analyze();
```
Getting the error:

```
Unhandled exception. System.ArgumentException: File does not exists (Parameter 'filePath')
   at Deque.AxeCore.Commons.FileAxeScriptProvider..ctor(String filePath)
   at AxeTest.SeleniumTests.Main() in /Users/dq_user/Desktop/selenium-nuint/Test.cs:line 24
```
@michael-siek  or @Zidious  can any one please provide correct syntax to use custom axeSource

**Comment by Zidious** [comment]
`axe-large-partial.js` in this case is just overriding `axe.runPartial` to return 250k nodes, you'll need to pass it an axe-source so it can finish the run as it normally would. I have an `axe-source.js` and `axe-large-partials.js`, you'll need to pass both (similar will apply to Playwright) to the Selenium AxeBuilder: 

```c#
using Deque.AxeCore.Commons;
using Deque.AxeCore.Selenium;
using OpenQA.Selenium.Chrome;


public class Program
{
    public static void Main(string[] args)
    {

      var driver = new ChromeDriver();
      driver.Url = "https://www.google.com";
      

      var axeSource = File.ReadAllText("./axe-source.js");
      var largePartials = File.ReadAllText("./axe-large-partial.js");

      var axeBuilder = new AxeBuilder(driver, new AxeBuilderOptions() {
        ScriptProvider = new StringAxeScriptProvider($"{axeSource}{largePartials}")
      });

      AxeResult results = axeBuilder.Analyze();

      // Do something with the results


      driver.Quit();
      
    }
}
```

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core-nuget' - 

with the extremely large files, `axe-large-partial.js` has  just overriding `axe.runPartial` to return 250k nodes. Analyse on `www.google.com` page expected `document-id` should notify.

Output is like:

```
Axe Results:
{
  "violations": [],
  "passes": [
    {
      "id": "duplicate-id",
      "description": "Ensures every id attribute value is unique",
      "help": "id attribute value must be unique",
      "helpUrl": "https://dequeuniversity.com/rules/axe/4.8/duplicate-id?application=axe-core-selenium-nuget",
      "impact": null,
      "tags": [
        "cat.parsing",
        "wcag2a-obsolete",
        "wcag411",
        "deprecated"
      ],
      "nodes": [
        {
          "target": "#fixture",
          "xPath": null,
          "ancestry": null,
          "html": "<div id=\"fixture\"></div>",
          "impact": null,
          "any": [
            {
              "data": "fixture",
              "id": "duplicate-id",
              "impact": "minor",
              "message": "Document has no static elements that share the same id attribute",
              "relatedNodes": []
            }
          ],
          "all": [],
          "none": []
        }
      ]
    }
  ],
  "inapplicable": [],
  "incomplete": [],
  "timestamp": "2023-02-01T22:53:38.103+00:00",
  "testEnvironment": {
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "windowWidth": 1109,
    "windowHeight": 946,
    "orientationType": "landscape-primary",
    "orientationAngle": 0.0
  },
  "testRunner": {
    "name": "axe"
  },
  "url": "http://localhost:9876/test/playground.html",
  "testEngine": {
    "name": "axe-core",
    "version": "4.6.3"
  },
  "toolOptions": {
    "reporter": "v1"
  }
}
```
Code verified for this is -

```

// #nullable enable
using Deque.AxeCore.Commons;
using Deque.AxeCore.Playwright;
using Deque.AxeCore.Selenium;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Remote;
using System;
using System.Diagnostics;
using System.Collections.Generic;
using FluentAssertions;
using WebDriverManager;
using WebDriverManager.DriverConfigs.Impl;
using System.IO;

public class Program
{
    public static void Main(string[] args)
    {
     var options = new ChromeOptions();
     IWebDriver webDriver = new ChromeDriver(options);
     webDriver.Navigate().GoToUrl("https://www.google.com");
      var axeSource = File.ReadAllText("./axe-source.js");
      var largePartials = File.ReadAllText("./axe-large-partial.js");
     var axeBuilder = new AxeBuilder(webDriver, new AxeBuilderOptions() { 
       ScriptProvider = new StringAxeScriptProvider($"{axeSource}{largePartials}")
     });
   
     AxeResult results = axeBuilder.Analyze();
      Console.WriteLine("Axe Results:");
      Console.WriteLine(results);
      // Do something with the results
     Console.WriteLine($"Number of Violations: {results.Violations.Length}");

      webDriver.Quit();
      
    }
   }
```

https://github.com/dequelabs/axe-core-nuget/assets/47409579/77092056-f055-4422-bbe8-f3adb7ced6b5
