### ISSUE TITLE
Playwright: getting error "Executable doesn't exist for chromium"

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-nuget#85]
##Steps to reproduce:
1. Installed the package for Playwright and required dependencies  for `Deque.AxeCore.Playwright` - `test.csproj`
2. Configured `nuget.config`
3. Created a test 
```
using System.Threading.Tasks;
using Microsoft.Playwright;
using Deque.AxeCore.Playwright;
using Deque.AxeCore.Commons;
class Program
{
    public static async Task Main()
    {
       using var playwright = await Playwright.CreateAsync();
       await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
        var page = await browser.NewPageAsync();
        await page.GotoAsync("http://qateam.dequecloud.com/attest/api/test.html");
        AxeResult axeResults = await page.RunAxe();
    }
}
```
4. Compited the test with `dotnet build` - build successfully
5. Tried  to run with `dotnet run` 
Getting error:
```
Unhandled exception. Microsoft.Playwright.PlaywrightException: Executable doesn't exist at /Users/dq_user/Library/Caches/ms-playwright/chromium-978106/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     pwsh bin\Debug\netX\playwright.ps1 install                          ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 161
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 61
   at Program.Main() in /Users/dq_user/Desktop/C#/NUnit/Example.cs:line 17
   at Program.<Main>()
```

## Which package were you using when you encountered the issue?**
- [ ] Deque.AxeCore.Playwright

## Expected behavior

Should run successfully

## Screenshots
<img width="1189" alt="image" src="https://github.com/dequelabs/axe-core-nuget/assets/47409579/4f47d632-9299-4639-8193-0db5ff4e10ed">

## Device Information
 - OS: MacOS - 11.6.8
 - Browser - Chromium
 - Deque.AxeCore-playwright- 4.4.0-alpha.c9651f2c2284967c64d2f28e460b5181d0af5c6d (When I tried to add 4.4.0 while comipling system suggested to use 4.4.0-alpha.c9651f2c2284967c64d2f28e460b5181d0af5c6d )

## Additional context
Tried to add latest Chromium using `npx playwright install chromium` not getting any resolution

**Comment by padmavemulapati** [comment]
Verified this as part of Release regression, using the build -  `Deque.AxeCore.Commons-4.7.2-alpha.49` 



![Image](https://github.com/dequelabs/axe-core-nuget/assets/47409579/49a2879b-472c-4aa3-9894-ca50daf1aa97)
